[programs.localnet]
solblog = "4WfX3TMZ8pv2FgQyLeWabRoJy5GAYAm7tZhkVGVdsUt7"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/Users/helenamerk/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

